import { createHash } from 'crypto';
import { getRuleQueryText, RuleMetadata, tacticDisplayName } from './ruleMetadata';

export interface AnalyticsRuleYamlOptions {
    /** Stable id derived from title when omitted */
    id?: string;
}

/**
 * Build a Microsoft Sentinel scheduled analytics rule YAML stub
 * suitable for detection-as-code repos (ARM/Bicep/YAML pipelines).
 */
export function buildAnalyticsRuleYaml(
    documentText: string,
    rule: RuleMetadata,
    options: AnalyticsRuleYamlOptions = {}
): string {
    const query = getRuleQueryText(documentText, rule);
    const id = options.id ?? stableRuleId(rule.title);
    const severity = rule.severity ?? 'Medium';
    const description = rule.description ?? rule.title;
    const queryFrequency = rule.queryFrequency ?? '1h';
    const queryPeriod = rule.queryPeriod ?? queryFrequency;
    const triggerOperator = rule.triggerOperator ?? 'gt';
    const triggerThreshold = rule.triggerThreshold ?? '0';

    const tactics = rule.tactics.length > 0
        ? rule.tactics
        : [];
    const techniques = rule.techniques;

    const lines: string[] = [
        `# Generated by KQL Assistant — review before deploying to Sentinel`,
        `id: ${id}`,
        `name: ${yamlScalar(rule.title)}`,
        `description: |`,
        ...description.split('\n').map(line => `  ${line}`),
        `severity: ${severity}`,
        `requiredDataConnectors: []`,
        `queryFrequency: ${queryFrequency}`,
        `queryPeriod: ${queryPeriod}`,
        `triggerOperator: ${triggerOperator}`,
        `triggerThreshold: ${triggerThreshold}`,
        `status: Available`,
        `tactics:`
    ];

    if (tactics.length === 0) {
        lines.push('  []');
    } else {
        for (const tactic of tactics) {
            lines.push(`  - ${tacticDisplayName(tactic)}`);
        }
    }

    lines.push('relevantTechniques:');
    if (techniques.length === 0) {
        lines.push('  []');
    } else {
        for (const technique of techniques) {
            lines.push(`  - ${technique}`);
        }
    }

    lines.push('query: |');
    if (query.trim() === '') {
        lines.push('  # (empty query)');
    } else {
        for (const line of query.split('\n')) {
            lines.push(`  ${line}`);
        }
    }

    lines.push('entityMappings: []');
    lines.push('version: 1.0.0');
    lines.push('kind: Scheduled');
    lines.push('');

    return lines.join('\n');
}

function yamlScalar(value: string): string {
    if (/[:#{}[\],&*?|>!%@`]/.test(value) || value.includes("'") || value.includes('"')) {
        return JSON.stringify(value);
    }
    return value;
}

function stableRuleId(title: string): string {
    const hash = createHash('sha1').update(title).digest('hex');
    // Format as UUID-like for Sentinel rule id fields
    return [
        hash.slice(0, 8),
        hash.slice(8, 12),
        '4' + hash.slice(13, 16),
        ((parseInt(hash.slice(16, 18), 16) & 0x3f) | 0x80).toString(16).padStart(2, '0') +
            hash.slice(18, 20),
        hash.slice(20, 32)
    ].join('-');
}
